### ISSUE TITLE
ESLint vs JSHint

### ISSUE THREAD

**Issue by mdjnewman** [Bahmni/openmrs-module-bahmniapps#37]
Hi!

Currently there is an .eslintrc file & a .jshintrc file checked in.

ESLint is used by Code Climate, whereas JSHint is used by the Grunt build.

There are also 2 errors & 571 warnings in the current .jshintrc output, so I'm wondering how much value it's providing (even errors don't fail the build).

I think it would be good to:
1. Standardise on one of these  (I'd prefer ESLint)
2. Chose what linting rules we actually care about, and make them fail the build
3. Remove all the other rules

Rules that just case warnings and don't break the build will be ignored most of the time, and just produce noise.

I'm happy to fix all the lint errors I can and change Grunt tasks if necessary, but I need some direction on which linter to use.  If we need ESLint to make use of Code Climate & want to keep the build using JSHint we should at least document why there are two, and configure them with similar rules, but I really think having just one is a better option.

Thoughts?

**Comment by bharatak** [comment]
@mdjnewman Thanks a lot.  We would prefer to go by eslint.  Our other projects like [form-controls](https://github.com/Bahmni/form-controls) and [implementer interface](https://github.com/Bahmni/implementer-interface) use eslint.  They are ReactJS + ES6 projects and eslint is the standard.  We can standardize it across bahmni.  Its a good idea to follow [johnpapa's style guide](https://github.com/johnpapa/angular-styleguide/tree/master/a1).  Looks like there is an [npm package](https://www.npmjs.com/package/eslint-plugin-angular) implementing it.

I am thinking of the following tasks
- Change the Grunt tasks to use ESLint
- Fail the build on lint errors
- Have the styles that are compatible today and fix some very obvious errors.  If you have a big list to fix, I prefer multiple PRs and doing it slowly.  Just trying to be cautious.
- You can comment out (but still keeping it in .eslintrc) the rules that bahmni is not compatible with currently, but are good to have.  We can work on it as a tech debt to slowly incorporate one rule at-a-time.

Appreciate your efforts.

**Comment by mdjnewman** [comment]
Thanks @bharatak, makes sense to standardise these things across projects. form-controls and implementer-interface use [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) which we can also use as a base.

eslint-plugin-angular sounds good, and it's [supported by Code Climate](https://docs.codeclimate.com/docs/eslint). We can add rules from this plugin to the airbnb base.

If eslint-config-airbnb isn't usable in openmrs-module-bahmniapps, [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) is another option for a base set of rules.

Those steps all make sense to me, fully agree gradually implementing rules as we make the code compatible is the best approach. I'd guess that JSHint is mostly being ignored at the moment anyway, so I don't think we lose anything by switching it to ESLint even if we have less rules initially.

I'll make a start on this before the weekend hopefully :)

I will make sure the build is green on Travis before I start. The current errors all seem to be around the [MyReportsController](https://travis-ci.org/Bahmni/openmrs-module-bahmniapps/jobs/170393253#L7034). I'm happy to look into this (I'm guessing it's something to do with timestamps) but if anyone on the core team wants to take a look and be responsible for keeping Travis green that would help.

**Comment by mdjnewman** [comment]
I had a chance to look into a suitable base set of rules.

The following config (using https://www.npmjs.com/package/eslint-config-angular)

```yaml
ecmaFeatures:
  modules: true
  jsx: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true

extends:
  - angular

globals:
  Bahmni: true
  EncounterConfig : true
  defaults : true
  describe: false
  it: false
  moment: false
  angular: false
  _: false
  d3: false
  c3: false
  expect: false
  window: false
  purl : false
  Modernizr: false
  AndroidOfflineService : false
  AndroidConfigDbService : false
  lf : false
  CryptoJS : false
  keyboardJS : false
  FastClick : false
```

results in 1634 problems (1560 errors, 74 warnings). Top 5 rule violations are:

```
  74 You should use angular.element instead of the jQuery $ object - angular/angularelement
 101 You should prefer the factory() method instead of service() - angular/no-service-method
 123 You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined - angular/definedundefined
 301 You should use the function syntax for DI - angular/di
 820 You should not set properties on $scope in controllers. Use controllerAs syntax and add data to "this" - angular/controller-as
```

Using the `airbnb` base like the other two projects results in way more warnings - I think eslint-config-angular + eslint-config-standard/semistandard is the way to go for now, with most rules disabled initially :)
